//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.example.autoservice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.autoservice package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.autoservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AutoService }
     * 
     * @return
     *     the new instance of {@link AutoService }
     */
    public AutoService createAutoService() {
        return new AutoService();
    }

    /**
     * Create an instance of {@link AutoService.Orders }
     * 
     * @return
     *     the new instance of {@link AutoService.Orders }
     */
    public AutoService.Orders createAutoServiceOrders() {
        return new AutoService.Orders();
    }

    /**
     * Create an instance of {@link AutoService.Orders.Order }
     * 
     * @return
     *     the new instance of {@link AutoService.Orders.Order }
     */
    public AutoService.Orders.Order createAutoServiceOrdersOrder() {
        return new AutoService.Orders.Order();
    }

    /**
     * Create an instance of {@link AutoService.Orders.Order.Services }
     * 
     * @return
     *     the new instance of {@link AutoService.Orders.Order.Services }
     */
    public AutoService.Orders.Order.Services createAutoServiceOrdersOrderServices() {
        return new AutoService.Orders.Order.Services();
    }

    /**
     * Create an instance of {@link AutoService.Cars }
     * 
     * @return
     *     the new instance of {@link AutoService.Cars }
     */
    public AutoService.Cars createAutoServiceCars() {
        return new AutoService.Cars();
    }

    /**
     * Create an instance of {@link AutoService.Clients }
     * 
     * @return
     *     the new instance of {@link AutoService.Clients }
     */
    public AutoService.Clients createAutoServiceClients() {
        return new AutoService.Clients();
    }

    /**
     * Create an instance of {@link AutoService.Orders.Order.Services.Service }
     * 
     * @return
     *     the new instance of {@link AutoService.Orders.Order.Services.Service }
     */
    public AutoService.Orders.Order.Services.Service createAutoServiceOrdersOrderServicesService() {
        return new AutoService.Orders.Order.Services.Service();
    }

    /**
     * Create an instance of {@link AutoService.Cars.Car }
     * 
     * @return
     *     the new instance of {@link AutoService.Cars.Car }
     */
    public AutoService.Cars.Car createAutoServiceCarsCar() {
        return new AutoService.Cars.Car();
    }

    /**
     * Create an instance of {@link AutoService.Clients.Client }
     * 
     * @return
     *     the new instance of {@link AutoService.Clients.Client }
     */
    public AutoService.Clients.Client createAutoServiceClientsClient() {
        return new AutoService.Clients.Client();
    }

}
