//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.example.autoservice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.autoservice package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.autoservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AutoService }
     * 
     * @return
     *     the new instance of {@link AutoService }
     */
    public AutoService createAutoService() {
        return new AutoService();
    }

    /**
     * Create an instance of {@link AutoService.Order }
     * 
     * @return
     *     the new instance of {@link AutoService.Order }
     */
    public AutoService.Order createAutoServiceOrder() {
        return new AutoService.Order();
    }

    /**
     * Create an instance of {@link AutoService.Order.Services }
     * 
     * @return
     *     the new instance of {@link AutoService.Order.Services }
     */
    public AutoService.Order.Services createAutoServiceOrderServices() {
        return new AutoService.Order.Services();
    }

    /**
     * Create an instance of {@link AutoService.Client }
     * 
     * @return
     *     the new instance of {@link AutoService.Client }
     */
    public AutoService.Client createAutoServiceClient() {
        return new AutoService.Client();
    }

    /**
     * Create an instance of {@link AutoService.Car }
     * 
     * @return
     *     the new instance of {@link AutoService.Car }
     */
    public AutoService.Car createAutoServiceCar() {
        return new AutoService.Car();
    }

    /**
     * Create an instance of {@link AutoService.Order.Services.Service }
     * 
     * @return
     *     the new instance of {@link AutoService.Order.Services.Service }
     */
    public AutoService.Order.Services.Service createAutoServiceOrderServicesService() {
        return new AutoService.Order.Services.Service();
    }

}
