//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://example.com/auto-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.autoservice;
